"""
Plot script for Exercise 3 - Change of variables: Y = U^2.

This script reads samples generated by change_variables_y_u2.c and compares
their histogram with the analytic density:

    f_Y(y) = 1 / (2 sqrt(y))

for 0 < y <= 1.

Expected input file:
    change_variables_y_u2.txt

Expected columns:
    y

Run:
    python3 plot.py
"""

import numpy as np
import matplotlib.pyplot as plt


def analytic_density(y):
    """Analytic density of Y = U^2, with U uniform in [0, 1]."""
    return 1.0 / (2.0 * np.sqrt(y))


def main():
    input_file = "change_variables_y_u2.txt"
    output_plot = "change_variables_y_u2_histogram.png"

    # Read generated samples.
    # Header lines beginning with "#" are ignored.
    y_samples = np.loadtxt(input_file)

    # Points for the analytic curve.
    # We avoid y = 0 because the density diverges there.
    y_grid = np.linspace(1.0e-4, 1.0, 1000)
    density = analytic_density(y_grid)

    plt.figure()

    # Normalized histogram.
    # density=True makes the area under the histogram approximately 1.
    plt.hist(
        y_samples,
        bins=80,
        density=True,
        alpha=0.6,
        label="simulation histogram",
    )

    # Analytic probability density.
    plt.plot(
        y_grid,
        density,
        linewidth=2,
        label=r"analytic density $1/(2\sqrt{y})$",
    )

    plt.xlabel("y")
    plt.ylabel("density")
    plt.title(r"Change of variables: $Y = U^2$")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()

    plt.savefig(output_plot, dpi=200)
    plt.close()

    print(f"Plot saved to: {output_plot}")


if __name__ == "__main__":
    main()