"""
Plot script for Exercise 5 - Empirical CDF for an exponential sample.

This script reads the empirical CDF data generated by empirical_cdf_exponential.c
and compares it with the exact exponential CDF:

    F(y) = 1 - exp(-lambda y)

with lambda = 1.5.

Expected input file:
    empirical_cdf_exponential.txt

Expected columns:
    y_sorted    empirical_cdf

Run:
    python3 plot.py
"""

import numpy as np
import matplotlib.pyplot as plt


LAMBDA = 1.5


def exact_cdf(y):
    """Exact CDF of the exponential distribution."""
    return 1.0 - np.exp(-LAMBDA * y)


def main():
    input_file = "empirical_cdf_exponential.txt"
    output_plot = "empirical_cdf_exponential.png"
    output_error_plot = "empirical_cdf_exponential_error.png"

    # Read the C output.
    # Lines starting with "#" are ignored automatically.
    data = np.loadtxt(input_file)

    y_sorted = data[:, 0]
    empirical_cdf = data[:, 1]

    # Exact CDF evaluated at the same sample points.
    exact_values = exact_cdf(y_sorted)

    # ------------------------------------------------------------
    # Plot 1: empirical CDF vs exact CDF
    # ------------------------------------------------------------
    plt.figure()

    # A step plot is natural for an empirical CDF.
    plt.step(
        y_sorted,
        empirical_cdf,
        where="post",
        label="empirical CDF",
    )

    plt.plot(
        y_sorted,
        exact_values,
        linewidth=2,
        label=r"exact CDF $1-e^{-\lambda y}$",
    )

    plt.xlabel("y")
    plt.ylabel("CDF")
    plt.title("Empirical CDF of exponential sample")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()

    plt.savefig(output_plot, dpi=200)
    plt.close()

    # ------------------------------------------------------------
    # Plot 2: absolute difference between empirical and exact CDF
    # ------------------------------------------------------------
    abs_error = np.abs(empirical_cdf - exact_values)

    plt.figure()

    plt.plot(
        y_sorted,
        abs_error,
        label="absolute CDF error",
    )

    plt.xlabel("y")
    plt.ylabel(r"$|F_n(y)-F(y)|$")
    plt.title("Empirical CDF error")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()

    plt.savefig(output_error_plot, dpi=200)
    plt.close()

    print("Plots saved:")
    print(f"  {output_plot}")
    print(f"  {output_error_plot}")


if __name__ == "__main__":
    main()