"""
Plot script for Exercise 4 - Inverse transform exponential sampling.

This script reads samples generated by inverse_transform_exponential.c and
compares their histogram with the analytic exponential PDF:

    f(y) = lambda * exp(-lambda y)

with lambda = 1.5.

Expected input file:
    inverse_transform_exponential.txt

Expected columns:
    y

Run:
    python3 plot.py
"""

import numpy as np
import matplotlib.pyplot as plt


LAMBDA = 1.5


def exponential_pdf(y):
    """Analytic exponential probability density function."""
    return LAMBDA * np.exp(-LAMBDA * y)


def main():
    input_file = "inverse_transform_exponential.txt"
    output_plot = "inverse_transform_exponential_histogram.png"

    # Read generated samples.
    # Lines beginning with "#" are ignored automatically.
    y_samples = np.loadtxt(input_file)

    # Build a grid for the analytic curve.
    # The exponential distribution is defined on y >= 0.
    # We stop at a high quantile to avoid a plot dominated by a few rare,
    # very large samples.
    y_max = np.quantile(y_samples, 0.995)
    y_grid = np.linspace(0.0, y_max, 1000)
    density = exponential_pdf(y_grid)

    plt.figure()

    # Normalized histogram of the generated samples.
    # density=True makes the histogram area approximately equal to 1.
    plt.hist(
        y_samples,
        bins=80,
        density=True,
        alpha=0.6,
        label="simulation histogram",
    )

    # Analytic PDF.
    plt.plot(
        y_grid,
        density,
        linewidth=2,
        label=r"analytic PDF $\lambda e^{-\lambda y}$",
    )

    plt.xlabel("y")
    plt.ylabel("density")
    plt.title(r"Inverse transform sampling: exponential distribution")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()

    plt.savefig(output_plot, dpi=200)
    plt.close()

    print(f"Plot saved to: {output_plot}")


if __name__ == "__main__":
    main()